### PR TITLE
Normative: rename fix -> transferToFixedLength

### PR DESCRIPTION
**Pull request by syg**

### CODE REVIEW

**Comment by syg** [comment]
@ljharb @anonrig any preference on the name?

**Review by anonrig — APPROVED** [review]
I'm 100% in favor of this change. Thanks!

**Review by ljharb — APPROVED** [review]
I prefer `transferFixed` over this much more verbose alternative, but either is certainly more clear than "fix".

**Comment by syg** [comment]
I initially prefer `transferFixed` as well, but one of the original confusions I thought was the word "fix" was confused for like, fixing something that's broken instead of making the length fixed. In the end I chose the more verbose alternative because I expect the usage to be relatively minor.

**Pull request merged**
